<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="..\StackContract.Core\StackContract.Core.csproj" /></ItemGroup>
  <ItemGroup><PackageReference Include="YamlDotNet" Version="18.1.0" /></ItemGroup>
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><PackageId>StackContract.Compose</PackageId><RootNamespace>StackContract.Compose</RootNamespace><AssemblyName>StackContract.Compose</AssemblyName><Version>0.1.0</Version><Authors>Manuwel Munyai</Authors><PackageLicenseExpression>MIT</PackageLicenseExpression><RepositoryUrl>https://github.com/munyaimanuwel/stackcontract</RepositoryUrl><PackageProjectUrl>https://github.com/munyaimanuwel/stackcontract</PackageProjectUrl><GeneratePackageOnBuild>false</GeneratePackageOnBuild></PropertyGroup>
</Project>
